export const productsData = [
  {
    id: 1,
    title: "Premium Cotton T-Shirt",
    description:
      "Soft 100% cotton t-shirt designed for daily comfort and durability.",
    category: "Men",
    brand: "UrbanStyle",
    price: 18.99,
    discountPrice: 14.99,
    inStock: true,
    stockQuantity: 150,
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["White", "Black", "Gray"],
    material: "100% Cotton",
    rating: 4.5,
    reviewCount: 234,
    images: [
      "https://images.pexels.com/photos/1040945/pexels-photo-1040945.jpeg",
      "https://images.pexels.com/photos/2905238/pexels-photo-2905238.jpeg",
    ],
  },
  {
    id: 2,
    title: "Slim Fit Denim Jeans",
    description:
      "Stylish slim-fit jeans with stretchable denim for maximum comfort.",
    category: "Men",
    brand: "DenimWave",
    price: 49.99,
    discountPrice: 39.99,
    inStock: true,
    stockQuantity: 90,
    sizes: ["30", "32", "34", "36", "38"],
    colors: ["Blue", "Dark Blue"],
    material: "Denim Stretch Fabric",
    rating: 4.7,
    reviewCount: 198,
    images: [
      "https://images.pexels.com/photos/2983464/pexels-photo-2983464.jpeg",
      "https://images.pexels.com/photos/1139743/pexels-photo-1139743.jpeg",
    ],
  },
  {
    id: 3,
    title: "Floral Summer Dress",
    description: "Lightweight floral dress perfect for summer outings.",
    category: "Women",
    brand: "Elegance",
    price: 59.99,
    discountPrice: 44.99,
    inStock: true,
    stockQuantity: 200,
    sizes: ["S", "M", "L"],
    colors: ["Red", "Yellow", "Pink"],
    material: "Polyester Blend",
    rating: 4.8,
    reviewCount: 321,
    images: [
      "https://images.pexels.com/photos/428338/pexels-photo-428338.jpeg",
      "https://images.pexels.com/photos/2801999/pexels-photo-2801999.jpeg",
    ],
  },
  {
    id: 4,
    title: "Men's Hooded Sweatshirt",
    description: "Warm and cozy hoodie suitable for winter season.",
    category: "Men",
    brand: "CozyWear",
    price: 39.99,
    discountPrice: 29.99,
    inStock: true,
    stockQuantity: 120,
    sizes: ["M", "L", "XL"],
    colors: ["Black", "Gray", "Navy"],
    material: "Fleece Cotton",
    rating: 4.6,
    reviewCount: 178,
    images: [
      "https://images.pexels.com/photos/767972/pexels-photo-767972.jpeg",
      "https://images.pexels.com/photos/1040881/pexels-photo-1040881.jpeg",
    ],
  },
  {
    id: 5,
    title: "Women's High Waist Leggings",
    description: "Flexible and breathable leggings ideal for workouts.",
    category: "Women",
    brand: "FlexFit",
    price: 25.99,
    discountPrice: 19.99,
    inStock: true,
    stockQuantity: 180,
    sizes: ["S", "M", "L", "XL"],
    colors: ["Black", "Gray"],
    material: "Nylon + Spandex",
    rating: 4.4,
    reviewCount: 152,
    images: [
      "https://images.pexels.com/photos/6311651/pexels-photo-6311651.jpeg",
      "https://images.pexels.com/photos/4325466/pexels-photo-4325466.jpeg",
    ],
  },
  {
    id: 6,
    title: "Kids Cartoon T-Shirt",
    description: "Soft cotton T-shirt with cute cartoon character print.",
    category: "Kids",
    brand: "Kiddo",
    price: 12.99,
    discountPrice: 9.99,
    inStock: true,
    stockQuantity: 140,
    sizes: ["XS", "S", "M", "L"],
    colors: ["Blue", "Pink", "Yellow"],
    material: "100% Cotton",
    rating: 4.3,
    reviewCount: 89,
    images: [
      "https://images.pexels.com/photos/3662841/pexels-photo-3662841.jpeg",
      "https://images.pexels.com/photos/3661185/pexels-photo-3661185.jpeg",
    ],
  },
  {
    id: 7,
    title: "Women's Denim Jacket",
    description: "Trendy denim jacket for a stylish casual look.",
    category: "Women",
    brand: "StyleHub",
    price: 69.99,
    discountPrice: 54.99,
    inStock: true,
    stockQuantity: 60,
    sizes: ["S", "M", "L", "XL"],
    colors: ["Blue", "Dark Blue"],
    material: "Pure Denim",
    rating: 4.7,
    reviewCount: 205,
    images: [
      "https://images.pexels.com/photos/428340/pexels-photo-428340.jpeg",
      "https://images.pexels.com/photos/428339/pexels-photo-428339.jpeg",
    ],
  },
  {
    id: 8,
    title: "Men's Polo Shirt",
    description: "Classic polo shirt suitable for both casual and formal wear.",
    category: "Men",
    brand: "GentleWear",
    price: 22.99,
    discountPrice: 18.99,
    inStock: true,
    stockQuantity: 110,
    sizes: ["M", "L", "XL", "XXL"],
    colors: ["Green", "Navy", "White"],
    material: "Pique Cotton",
    rating: 4.5,
    reviewCount: 167,
    images: [
      "https://images.pexels.com/photos/762020/pexels-photo-762020.jpeg",
      "https://images.pexels.com/photos/2983466/pexels-photo-2983466.jpeg",
    ],
  },
  {
    id: 9,
    title: "Kids Winter Jacket",
    description: "Warm and soft winter jacket designed for kids.",
    category: "Kids",
    brand: "SnowKids",
    price: 45.99,
    discountPrice: 36.99,
    inStock: true,
    stockQuantity: 70,
    sizes: ["S", "M", "L"],
    colors: ["Red", "Blue", "Gray"],
    material: "Polyester + Fleece",
    rating: 4.6,
    reviewCount: 142,
    images: [
      "https://images.pexels.com/photos/3261060/pexels-photo-3261060.jpeg",
      "https://images.pexels.com/photos/3109836/pexels-photo-3109836.jpeg",
    ],
  },
  {
    id: 10,
    title: "Silk Printed Scarf",
    description: "Elegant silk scarf with unique premium patterns.",
    category: "Women",
    brand: "LuxurySilk",
    price: 19.99,
    discountPrice: 15.99,
    inStock: true,
    stockQuantity: 200,
    sizes: ["Free Size"],
    colors: ["Purple", "White", "Pink"],
    material: "100% Silk",
    rating: 4.9,
    reviewCount: 310,
    images: [
      "https://images.pexels.com/photos/428341/pexels-photo-428341.jpeg",
      "https://images.pexels.com/photos/428337/pexels-photo-428337.jpeg",
    ],
  },
];
