export const skincareProducts = [
  {
    id: 1,
    name: "CeraVe Hydrating Facial Cleanser",
    category: "Facewash",
    subcategory: "Cleanser",
    brand: "CeraVe",
    price: 14.99,
    discountPrice: 12.49,
    discount: 15,
    stock: 120,
    inStock: true,
    sold: 540,
    size: "236ml",
    skinType: ["Dry", "Sensitive"],
    ingredients: ["Ceramides", "Hyaluronic Acid", "Glycerin"],
    rating: 4.8,
    reviewCount: 823,
    isFeatured: true,
    tags: ["hydrating", "gentle", "dry skin"],
    slug: "cerave-hydrating-cleanser",
    description:
      "A gentle hydrating cleanser with ceramides and hyaluronic acid. Best for dry and sensitive skin.",
    images: [
      "https://www.cerave.com/-/media/project/loreal/brand-sites/cerave/americas/us/skincare/cleansers/hydrating-facial-cleanser/photos/2025/hydrating-facial-cleanser_front.jpg",
      "https://www.cerave.com/-/media/project/loreal/brand-sites/cerave/americas/us/skincare/cleansers/hydrating-facial-cleanser/photos/2025/hydrating-facial-cleanser_back.jpg",
      "https://www.cerave.com/-/media/project/loreal/brand-sites/cerave/americas/us/new-pdp-images/lor2216_hydrating_cleanser_12oz-700x785-v1.jpg",
    ],
    createdAt: "2024-02-11",
    updatedAt: "2024-11-20",
  },

  {
    id: 2,
    name: "La Roche-Posay Effaclar Gel",
    category: "Facewash",
    subcategory: "Acne Control",
    brand: "La Roche-Posay",
    price: 19.99,
    discountPrice: 17.49,
    discount: 12,
    stock: 90,
    inStock: true,
    sold: 610,
    size: "200ml",
    skinType: ["Oily", "Acne-Prone"],
    ingredients: ["Salicylic Acid", "Zinc PCA"],
    rating: 4.7,
    reviewCount: 1100,
    isFeatured: false,
    tags: ["oil control", "acne treatment"],
    slug: "effaclar-gel-cleanser",
    description:
      "A deep-cleansing gel formulated for oily and acne-prone skin. Controls sebum and reduces breakouts.",
    images: [
      "https://www.laroche-posay.us/dw/image/v2/AANG_PRD/on/demandware.static/-/Sites-acd-laroche-posay-master-catalog/default/dw5a856f03/img/effaclargelcleanser/effaclar-facial-wash-for-oily-skin-3337872411991-1.jpg",
      "https://www.laroche-posay.us/dw/image/v2/AANG_PRD/on/demandware.static/-/Sites-acd-laroche-posay-master-catalog/default/dwaa34f2c5/img/effaclargelcleanser/007_Updates/LaRochePosay-Product-Effaclar-Effaclar-Foaming-Gel-400ml-3337872411991-Reco-REV.jpg",
      "https://www.laroche-posay.us/dw/image/v2/AANG_PRD/on/demandware.static/-/Sites-acd-laroche-posay-master-catalog/default/dw9d3d0901/img/effaclargelcleanser/007_Updates/LaRochePosay-Product-EffaclarGelCleanser-routine.jpg",
    ],
    createdAt: "2024-03-15",
    updatedAt: "2024-11-20",
  },

  {
    id: 3,
    name: "The Ordinary Niacinamide 10% + Zinc 1%",
    category: "Serum",
    subcategory: "Brightening",
    brand: "The Ordinary",
    price: 9.99,
    discountPrice: 8.49,
    discount: 15,
    stock: 200,
    inStock: true,
    sold: 1800,
    size: "30ml",
    skinType: ["Oily", "Acne-Prone"],
    ingredients: ["Niacinamide", "Zinc PCA"],
    rating: 4.6,
    reviewCount: 2100,
    isFeatured: true,
    tags: ["brightening", "acne reduction"],
    slug: "ordinary-niacinamide-serum",
    description: "Reduces blemishes, controls oil and brightens complexion.",
    images: [
      "https://theordinary.com/dw/image/v2/BFKJ_PRD/on/demandware.static/-/Sites-deciem-master/default/dwce8a7cdf/Images/products/The%20Ordinary/rdn-niacinamide-10pct-zinc-1pct-30ml.png",
      "https://theordinary.com/dw/image/v2/BFKJ_PRD/on/demandware.static/-/Sites-deciem-master/default/dw51b196c5/Images/products/The%20Ordinary/application/ord-niacinamide-10-zic-1-model-application-with-benefits.jpg",
      "https://theordinary.com/dw/image/v2/BFKJ_PRD/on/demandware.static/-/Sites-deciem-master/default/dwcf135ad6/Images/products/The%20Ordinary/Before-After/ord-niacinamide-zinc-blemish-serum-before-after-pores.jpg",
    ],
    createdAt: "2023-12-08",
    updatedAt: "2024-11-20",
  },

  {
    id: 4,
    name: "COSRX Advanced Snail 96 Mucin Power Essence",
    category: "Serum",
    subcategory: "Essence",
    brand: "COSRX",
    price: 25.99,
    discountPrice: 22.49,
    discount: 12,
    stock: 75,
    inStock: true,
    sold: 950,
    size: "100ml",
    skinType: ["Dry", "Sensitive"],
    ingredients: ["Snail Mucin 96%", "Hyaluronic Acid"],
    rating: 4.9,
    reviewCount: 3500,
    isFeatured: true,
    tags: ["hydrating", "repairing"],
    slug: "cosrx-snail-essence",
    description:
      "Deeply hydrating snail mucin serum that repairs and smooths skin.",
    images: [
      "https://www.cosrx.com/cdn/shop/files/james_800x1067_1_1_4e9750cc-2cd6-4817-ace5-be2305a85806_900x.jpg",
      "https://www.cosrx.com/cdn/shop/files/advanced-snail-96-mucin-power-essence-cosrx-official-6_900x.jpg",
      "https://www.cosrx.com/cdn/shop/files/advanced-snail-96-mucin-power-essence-cosrx-official-8_900x.jpg",
    ],
    createdAt: "2024-01-20",
    updatedAt: "2024-11-20",
  },

  {
    id: 5,
    name: "Cetaphil Moisturizing Cream",
    category: "Cream",
    subcategory: "Moisturizer",
    brand: "Cetaphil",
    price: 12.99,
    discountPrice: 10.99,
    discount: 15,
    stock: 160,
    inStock: true,
    sold: 700,
    size: "250g",
    skinType: ["Dry", "Sensitive"],
    ingredients: ["Glycerin", "Sweet Almond Oil"],
    rating: 4.5,
    reviewCount: 980,
    isFeatured: false,
    tags: ["moisturizing", "sensitive skin"],
    slug: "cetaphil-moisturizing-cream",
    description: "Gentle moisturizing cream for dry and sensitive skin.",
    images: [
      "https://www.cetaphil.com/dw/image/v2/BGGN_PRD/on/demandware.static/-/Sites-galderma-us-m-catalog/default/dwde5cbd08/Moisturizing%20Cream/052410_MC_16oz-Front.PNG",
      "https://www.cetaphil.com/dw/image/v2/BGGN_PRD/on/demandware.static/-/Sites-galderma-us-m-catalog/default/dwde5cbd08/Moisturizing%20Cream/052410_MC_16oz-Front.PNG",
    ],
    createdAt: "2024-02-01",
    updatedAt: "2024-11-20",
  },

  {
    id: 6,
    name: "Neutrogena Hydro Boost Water Gel",
    category: "Cream",
    subcategory: "Hydrating",
    brand: "Neutrogena",
    price: 18.99,
    discountPrice: 16.49,
    discount: 13,
    stock: 130,
    inStock: true,
    sold: 1020,
    size: "50ml",
    skinType: ["Oily", "Normal"],
    ingredients: ["Hyaluronic Acid"],
    rating: 4.8,
    reviewCount: 1400,
    isFeatured: true,
    tags: ["hydration", "gel moisturizer"],
    slug: "neutrogena-hydroboost-gel",
    description:
      "Lightweight gel moisturizer with hyaluronic acid for long-lasting hydration.",
    images: [
      "https://images.ctfassets.net/bcjr30vxh6td/249vyCPCWOePqx9Reg2Y7O/217ce1ad98092d44f138083ad7a1e1c0/6811047_Carousel_1.webp",
      "https://images.ctfassets.net/bcjr30vxh6td/56bUlON1hpJ4hnENdTn3uS/386174515859f36b52f8b15f9c7ded9f/6811047_Carousel_5.webp",
      "https://images.ctfassets.net/bcjr30vxh6td/2AOVUv1OO6PHQqOacVmwEM/34633847b871d4d1fae37dc7727aa444/6811047_Carousel_8.webp",
    ],
    createdAt: "2024-03-02",
    updatedAt: "2024-11-20",
  },

  {
    id: 7,
    name: "The Ordinary AHA 30% + BHA 2% Peeling Solution",
    category: "Serum",
    subcategory: "Exfoliating",
    brand: "The Ordinary",
    price: 12.49,
    discountPrice: 10.99,
    discount: 12,
    stock: 60,
    inStock: true,
    sold: 2200,
    size: "30ml",
    skinType: ["Oily", "Combination"],
    ingredients: ["AHA", "BHA"],
    rating: 4.6,
    reviewCount: 1900,
    isFeatured: false,
    tags: ["exfoliating", "glow"],
    slug: "ordinary-aha-bha-peel",
    description: "Powerful exfoliating solution for brighter, smoother skin.",
    images: [
      "https://theordinary.com/dw/image/v2/BFKJ_PRD/on/demandware.static/-/Sites-deciem-master/default/dwdf7a6213/Images/products/The%20Ordinary/rdn-aha-30pct-bha-2pct-peeling-solution-30ml.png",
      "https://theordinary.com/dw/image/v2/BFKJ_PRD/on/demandware.static/-/Sites-deciem-master/default/dwe5053a41/Images/products/The%20Ordinary/application/ord-aha-bha-peeling-solution-model-application-with-benefits.jpg",
      "https://theordinary.com/dw/image/v2/BFKJ_PRD/on/demandware.static/-/Sites-deciem-master/default/dw0b40a01b/Images/products/The%20Ordinary/infographics/ord-aha-bha-peeling-solution-ingredients-graphic.jpg",
    ],
    createdAt: "2024-05-08",
    updatedAt: "2024-11-20",
  },

  {
    id: 8,
    name: "Bioderma Atoderm Intensive Gel Moussant",
    category: "Facewash",
    subcategory: "Sensitive Skin",
    brand: "Bioderma",
    price: 15.99,
    discountPrice: 13.99,
    discount: 12,
    stock: 110,
    inStock: true,
    sold: 480,
    size: "500ml",
    skinType: ["Dry", "Sensitive"],
    ingredients: ["Niacinamide"],
    rating: 4.7,
    reviewCount: 720,
    isFeatured: false,
    tags: ["gentle", "moisturizing"],
    slug: "bioderma-atoderm-gel",
    description: "Gentle foaming gel for dry and sensitive skin.",
    images: [
      "https://bk.shajgoj.com/storage/2020/09/Bioderma-Atoderm-Intensive-Gel-Moussant-Ultra-Rich-Foaming-Gel.jpg",
      "https://bk.shajgoj.com/storage/2020/09/Bioderma-Atoderm-Intensive-Gel-Moussant-Ultra-Rich-Foaming-Gel.jpg",
    ],
    createdAt: "2024-04-18",
    updatedAt: "2024-11-20",
  },

  {
    id: 9,
    name: "Olay Regenerist Micro-Sculpting Cream",
    category: "Cream",
    subcategory: "Anti-aging",
    brand: "Olay",
    price: 28.99,
    discountPrice: 24.99,
    discount: 14,
    stock: 85,
    inStock: true,
    sold: 670,
    size: "50g",
    skinType: ["Mature", "Normal"],
    ingredients: ["Peptides", "Niacinamide"],
    rating: 4.6,
    reviewCount: 1550,
    isFeatured: true,
    tags: ["anti-aging", "firming"],
    slug: "olay-regenerist-cream",
    description:
      "Anti-aging moisturizer that hydrates, firms, and rejuvenates skin.",
    images: [
      "https://cdn11.bigcommerce.com/s-gud7r2x2lu/images/stencil/640w/attribute_rule_images/90_source_1749588512.jpg",
      "https://cdn11.bigcommerce.com/s-gud7r2x2lu/images/stencil/640w/products/505/7983/Olay_SI01_EN_MicroSculptingCream_Intro__45171.1749588388.jpg",
      "https://www.garnier.in/-/media/project/loreal/brand-sites/garnier/apac/in/products/light-complete/vitamin-c-face-serum/vitamin-c-face-serum-30ml/8994993011421-04.jpg",
    ],
    createdAt: "2024-03-20",
    updatedAt: "2024-11-20",
  },

  {
    id: 10,
    name: "Garnier Vitamin C Brightening Serum",
    category: "Serum",
    subcategory: "Brightening",
    brand: "Garnier",
    price: 13.49,
    discountPrice: 11.49,
    discount: 15,
    stock: 140,
    inStock: true,
    sold: 1300,
    size: "30ml",
    skinType: ["All Skin Types"],
    ingredients: ["Vitamin C", "Niacinamide"],
    rating: 4.4,
    reviewCount: 980,
    isFeatured: false,
    tags: ["vitamin c", "brightening"],
    slug: "garnier-vitamin-c-serum",
    description: "Brightening serum that reduces dark spots and boosts glow.",
    images: [
      "https://bk.shajgoj.com/storage/2022/08/Garnier-Skin-Active-Vitamin-C-Brightening-Serum-1.jpg",
      "https://bk.shajgoj.com/storage/2022/08/Garnier-Skin-Active-Vitamin-C-Brightening-Serum-3.jpg",
      "https://bk.shajgoj.com/storage/2022/08/Garnier-Skin-Active-Vitamin-C-Brightening-Serum-6.jpg",
    ],
    createdAt: "2024-04-10",
    updatedAt: "2024-11-20",
  },
  {
    id: 11,
    name: "La Roche-Posay Anthelios Ultra-Light SPF 50",
    category: "Sunscreen",
    subcategory: "Face",
    brand: "La Roche-Posay",
    price: 24.99,
    discountPrice: 21.99,
    discount: 12,
    stock: 100,
    inStock: true,
    sold: 500,
    size: "50ml",
    skinType: ["All Skin Types", "Sensitive"],
    ingredients: ["Mexoryl SX", "Glycerin", "Thermal Spring Water"],
    rating: 4.8,
    reviewCount: 1200,
    isFeatured: true,
    tags: ["spf50", "lightweight", "sensitive skin"],
    slug: "la-roche-posay-anthelios-spf50",
    description:
      "Broad-spectrum SPF 50 sunscreen, ultra-light and non-greasy. Perfect for sensitive skin.",
    images: [
      "https://bk.shajgoj.com/storage/2022/07/La-Roche-posay-Anthelios-Mineral-Ultra-Light-Sunscreen-Spf-50.jpg",
      "https://bk.shajgoj.com/storage/2022/07/La-Roche-posay-Anthelios-Mineral-Ultra-Light-Sunscreen-Spf-502.jpg",
      "https://bk.shajgoj.com/storage/2022/07/La-Roche-posay-Anthelios-Mineral-Ultra-Light-Sunscreen-Spf-504.jpg",
    ],
    createdAt: "2024-06-01",
    updatedAt: "2024-11-30",
  },

  {
    id: 12,
    name: "Neutrogena Ultra Sheer Dry-Touch SPF 55",
    category: "Sunscreen",
    subcategory: "Face",
    brand: "Neutrogena",
    price: 14.99,
    discountPrice: 12.99,
    discount: 13,
    stock: 120,
    inStock: true,
    sold: 800,
    size: "50ml",
    skinType: ["Oily", "Normal"],
    ingredients: ["Avobenzone", "Homosalate", "Octisalate"],
    rating: 4.7,
    reviewCount: 1100,
    isFeatured: true,
    tags: ["spf55", "oil-control", "matte finish"],
    slug: "neutrogena-ultra-sheer-spf55",
    description:
      "High-protection SPF 55 sunscreen with a dry-touch matte finish for oily and normal skin.",
    images: [
      "https://images.ctfassets.net/bcjr30vxh6td/rsxMVyeMGbNsndAZQpHtP/06a1257abd4c07dd6fcb1976cb9f8c57/6868790_Carousel1.webp",
      "https://images.ctfassets.net/bcjr30vxh6td/1ZUpfjCktaBrKyMp6zEr9C/27bf45daefc3bd4a9dcfb31a37e1df51/6868785_Carousel4.webp",
      "https://images.ctfassets.net/bcjr30vxh6td/4GMe6aznwlXSaC3Z5W91uz/79f4834b44d91c6640459fd341db8945/6868785_Carousel9.webp",
    ],
    createdAt: "2024-07-10",
    updatedAt: "2024-11-30",
  },
  {
    id: 13,
    name: "CeraVe Hydrating Mineral Sunscreen SPF 50",
    category: "Sunscreen",
    subcategory: "Face & Body",
    brand: "CeraVe",
    price: 19.99,
    discountPrice: 17.99,
    discount: 10,
    stock: 150,
    inStock: true,
    sold: 600,
    size: "88ml",
    skinType: ["Dry", "Sensitive"],
    ingredients: ["Zinc Oxide", "Titanium Dioxide", "Ceramides"],
    rating: 4.6,
    reviewCount: 750,
    isFeatured: false,
    tags: ["spf50", "hydrating", "mineral sunscreen"],
    slug: "cerave-hydrating-mineral-spf50",
    description:
      "Mineral sunscreen with SPF 50. Hydrating formula suitable for dry and sensitive skin.",
    images: [
      "https://www.cerave.com/-/media/project/loreal/brand-sites/cerave/americas/us/sunscreen/face/50-spf-face/50-spf-face_front.jpg",
    ],
    createdAt: "2024-06-15",
    updatedAt: "2024-11-30",
  },
  {
    id: 14,
    name: "Bioderma Photoderm Max SPF 50+",
    category: "Sunscreen",
    subcategory: "Face",
    brand: "Bioderma",
    price: 22.99,
    discountPrice: 19.99,
    discount: 13,
    stock: 90,
    inStock: true,
    sold: 450,
    size: "40ml",
    skinType: ["All Skin Types", "Sensitive"],
    ingredients: ["Avobenzone", "Octocrylene", "Glycerin"],
    rating: 4.7,
    reviewCount: 680,
    isFeatured: false,
    tags: ["spf50+", "sensitive skin", "broad-spectrum"],
    slug: "bioderma-photoderm-max-spf50",
    description:
      "High-protection sunscreen with SPF 50+ for sensitive skin. Lightweight and fast-absorbing.",
    images: [
      "https://www.bioderma.co.uk/sites/uk/files/styles/product_packshot_slider/public/products/%7B157084%7D_%7B%7D_%7B28560F%7D.jpg",
      "https://www.bioderma.co.uk/sites/uk/files/styles/product_packshot_slider/public/products/%7B83692%7D_%7B%7D_%7B28560F%7D.png",
    ],
    createdAt: "2024-07-05",
    updatedAt: "2024-11-30",
  },
  {
    id: 15,
    name: "Olay Regenerist Night Recovery Cream",
    category: "Night Cream",
    subcategory: "Anti-aging",
    brand: "Olay",
    price: 27.99,
    discountPrice: 24.99,
    discount: 11,
    stock: 80,
    inStock: true,
    sold: 500,
    size: "50g",
    skinType: ["Normal", "Mature"],
    ingredients: ["Niacinamide", "Peptides", "Hyaluronic Acid"],
    rating: 4.8,
    reviewCount: 1200,
    isFeatured: true,
    tags: ["anti-aging", "hydrating", "night cream"],
    slug: "olay-regenerist-night-cream",
    description:
      "Deeply hydrating night cream that reduces wrinkles and firms skin overnight.",
    images: [
      "https://www.skinplusbd.com/public/uploads/all/7AJoOFAuJW8Vwxytu7453DiYAySdXpTjpdhadGgB.webp",
      "https://www.skinplusbd.com/public/uploads/all/opH1rD0nH7gOxbdrpimOQjkvcLrOzpe3cWzPlGcW.webp",
    ],
    createdAt: "2024-05-01",
    updatedAt: "2024-11-30",
  },

  {
    id: 16,
    name: "L’Oreal Paris Revitalift Night Cream",
    category: "Night Cream",
    subcategory: "Anti-aging",
    brand: "L’Oreal Paris",
    price: 25.99,
    discountPrice: 22.99,
    discount: 12,
    stock: 85,
    inStock: true,
    sold: 350,
    size: "50ml",
    skinType: ["Mature", "Normal"],
    ingredients: ["Pro-Retinol", "Hyaluronic Acid"],
    rating: 4.8,
    reviewCount: 900,
    isFeatured: true,
    tags: ["anti-aging", "night cream", "firming"],
    slug: "loreal-revitalift-night",
    description:
      "Intensive anti-aging night cream with Pro-Retinol to reduce wrinkles and firm skin.",
    images: [
      "https://bk.shajgoj.com/storage/2021/09/LOreal-Revitalift-Hydrating-Night-Cream-1.jpg",
      "https://bk.shajgoj.com/storage/2021/09/LOreal-Revitalift-Hydrating-Night-Cream-3.jpg",
      "https://bk.shajgoj.com/storage/2021/09/LOreal-Revitalift-Hydrating-Night-Cream-4.jpg",
    ],
    createdAt: "2024-07-01",
    updatedAt: "2024-11-30",
  },
  {
    id: 17,
    name: "SKIN1004 Madagascar Centella Asiatica Ampoule",
    category: "Serum",
    subcategory: "Essence",
    brand: "SKIN1004",
    price: 28.99,
    discountPrice: 25.99,
    discount: 10,
    stock: 100,
    inStock: true,
    sold: 500,
    size: "50ml",
    skinType: ["All Skin Types"],
    ingredients: ["Centella Asiatica", "Adenosine"],
    rating: 4.8,
    reviewCount: 900,
    isFeatured: true,
    tags: ["soothing", "repairing", "serum"],
    slug: "skin1004-centella-ampoule",
    description:
      "Repairing serum enriched with Centella Asiatica for calm, healthy skin.",
    images: [
      "https://bk.shajgoj.com/storage/2024/10/skin1004-madagascar-centella-ampoule55ml.jpg",
      "https://bk.shajgoj.com/storage/2024/10/skin1004-madagascar-centella-ampoule55ml.jpg",
    ],
    createdAt: "2024-07-20",
    updatedAt: "2024-11-30",
  },
  {
    id: 18,
    name: "Cetaphil Gentle Skin Cleanser",
    category: "Facewash",
    subcategory: "Cleanser",
    brand: "Cetaphil",
    price: 10.99,
    discountPrice: 9.49,
    discount: 14,
    stock: 200,
    inStock: true,
    sold: 1500,
    size: "237ml",
    skinType: ["Dry", "Sensitive", "Normal"],
    ingredients: ["Water", "Cetyl Alcohol", "Propylene Glycol"],
    rating: 4.8,
    reviewCount: 2200,
    isFeatured: true,
    tags: ["gentle", "soothing", "daily cleanser"],
    slug: "cetaphil-gentle-skin-cleanser",
    description:
      "Mild, non-irritating cleanser suitable for all skin types including sensitive skin.",
    images: [
      "https://www.cetaphil.com/dw/image/v2/BGGN_PRD/on/demandware.static/-/Sites-galderma-us-m-catalog/default/dw554054cc/302990100624/GSC-RESIZE-1.2X.png",
      "https://www.cetaphil.com/dw/image/v2/BGGN_PRD/on/demandware.static/-/Sites-galderma-us-m-catalog/default/dwd59da384/Gentle%20Skin%20Cleanser/302990110227_CloseUp_Editorial_.jpg",
      "https://www.cetaphil.com/dw/image/v2/BGGN_PRD/on/demandware.static/-/Sites-galderma-us-m-catalog/default/dw26ceab2a/Gentle%20Skin%20Cleanser/302990110227_InUse_.jpg",
    ],
    createdAt: "2024-02-15",
    updatedAt: "2024-11-30",
  },
  {
    id: 19,
    name: "COSRX Low pH Good Morning Gel Cleanser",
    category: "Facewash",
    subcategory: "Cleanser",
    brand: "COSRX",
    price: 12.99,
    discountPrice: 10.99,
    discount: 15,
    stock: 180,
    inStock: true,
    sold: 1600,
    size: "150ml",
    skinType: ["Oily", "Acne-Prone", "Combination"],
    ingredients: ["BHA", "Tea Tree Extract"],
    rating: 4.7,
    reviewCount: 2000,
    isFeatured: true,
    tags: ["gentle", "acne control", "low ph"],
    slug: "cosrx-low-ph-cleanser",
    description:
      "Gentle gel cleanser with low pH for morning use, suitable for acne-prone skin.",
    images: [
      "https://www.cosrx.com/cdn/shop/files/low-ph-good-morning-gel-cleanser-cosrx-official-1_720x.jpg",
      "https://www.cosrx.com/cdn/shop/files/low-ph-good-morning-gel-cleanser-cosrx-official-4_720x.jpg",
      "https://www.cosrx.com/cdn/shop/files/low-ph-good-morning-gel-cleanser-cosrx-official-5_720x.jpg",
    ],
    createdAt: "2024-03-15",
    updatedAt: "2024-11-30",
  },
];

// export const categories = [
//   ...new Set(skincareProducts.map((item) => item.category)),
// ];
